Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Hello"
  
    config.vm.define "web01" do |web01|
      web01.vm.box = "ubuntu/focal64"
      web01.vm.hostname = "web01"
      web01.vm.network "private_network" , ip: "192.168.56.41"
    end

    config.vm.define "web02" do |web02|
        web02.vm.box = "ubuntu/focal64"
        web02.vm.hostname = "web02"
        web02.vm.network "private_network" , ip: "192.168.56.42"
      end
  
      config.vm.define "db01" do |db01|
        db01.vm.box = "centos/7"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network" , ip: "192.168.56.43"
        db01.vm.provision "shell", inline: <<-SHELL
        yum install -y apache2
        echo "<h1>Hello, Vagrant!</h1>" | sudo tee /var/www/html/index.html
        SHELL
      end
  end
  